import Head from 'next/head';
import { useState } from 'react';
import Footer from '../components/Footer';
import HireMe from '../components/HireMe';
import Navbar from '../components/Navbar';
import BeatStore from '../components/BeatStore';
import Faq from '../sections/Faq';
import Hero from '../sections/Hero';
import MarketPlace from '../sections/MarketPlace';
import Pricing from '../sections/Pricing';
import Services from '../sections/Services';
import Testimony from '../sections/Testimony';
import Yt from '../sections/Yt';

export default function Home() {
  const [showModal, setShowModal] = useState(false);

  function handleModal() {
    setShowModal(!showModal);
  }
  return (
    <div className="wrapper">
      <Head>
        <title>Max The Stranger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar handleModal={handleModal} />

      <main className="main">
        <Hero />
        <BeatStore />
        <MarketPlace />
        <Services />
        <Pricing />
        <Yt />
        <Faq />
        <Testimony />
      </main>

      <Footer />
      <HireMe showModal={showModal} handleModal={handleModal} />
    </div>
  );
}
